language: java
jdk:
- oraclejdk8
env:
  global:
  - TERM=dumb
  - secure: CdUW84T2E9pbdgn7k8gmdtY44vSLdDcMaxvbFjHxtj4hOauibNi6f7N8Iz1xNN62hqVhV2JEPtpyH1my3l8OUA6NfY/p5Qml51Q9mFMK3F4IG58EN30L0HxEzXKynPN9Sf00TXWG0DuXxPH1DPbYGGpBStSOOGwmuYKwFLOPUTM=
  - secure: MJq9a4NQLOM81D27CthsLoPaebKjOeMGcQA5RnZtBeSQrVEnO4CwkpUxb69LJV4BSAbutGyM6Imu22c1c1JKWlpCaOZHqro19L+fP6evSdmCLIH/seDI4z8Ldp35JC2FUIv3x5gWGxwvUsUAp5uRBZbeLs1aCqfGY/OwcruWtqs=
install:
- ./gradlew clean test build publish publishBintray
